### ISSUE TITLE
RealEngine doesn't run

### ISSUE THREAD

**Issue by thezocki** [zhaijialong/RealEngine#13]
When I try to run the engine, it crash and throws this error:
![image](https://github.com/user-attachments/assets/cc5f749d-d1e7-4c31-b44d-bcad74c24ecd)

**Comment by zhaijialong** [comment]
That's weird, I haven't met that before. What's the call stack when the crash happens?

**Comment by thezocki** [comment]
Of course, 
![image](https://github.com/user-attachments/assets/8b636ed6-5059-4992-bdfc-5f852adcd7e5)

**Comment by thezocki** [comment]
![image](https://github.com/user-attachments/assets/b08ccc47-91a8-474a-bacf-6594551d59c1)

**Comment by zhaijialong** [comment]
Well that's because I'm using a preview Agility SDK which requires developer mode enabled. Should be fixed in https://github.com/zhaijialong/RealEngine/commit/10844a35e86749ad7a2f888280ee4fcd233bacea

**Comment by thezocki** [comment]
It works now, thanks <3
